import pandas as pd
import os
import yaml

OUTPUT_DIR = r'outputs'
INPUT_FILEPATH = os.path.join(OUTPUT_DIR, 'processed_sea_results_with_uniprot_data.csv')
OUTPUT_FILEPATH = os.path.join(OUTPUT_DIR, 'yamls')

# def filterDf(df: pd.DataFrame, columns: list[str]):
#     '''
#     Removes rows of a specified df containing empty strings or NaN values in the specified columns and returns the df with index reset.
#     '''
    
#     df = df.dropna(subset=columns)
#     for column in columns:
#         df = df[df[column].str.strip().astype(bool)]
        
#     return df.reset_index(drop=True)

def generateBoltzYamls(proteinLigandPairs: pd.DataFrame, outputDir, chunk_size, cap=float('inf')):
    """
    Generates Boltz YAML files. The first file in each chunk is a 'Pilot' (no MSA key),
    while subsequent files point to the Pilot's generated MSA on the cluster.
    """
    if not os.path.exists(outputDir):
        os.makedirs(outputDir)
    
    subDirKey = []
    globalFileCount = 0
    folderCounter = 0
    
    print(f"Generating Boltz YAML files...")

    # group the df by protein ID
    grouped = proteinLigandPairs.groupby('UniProt ID')
    
    for uniprot_id, group in grouped:
        if globalFileCount >= cap:
            break
        
        num_ligands = len(group)
        for i in range(0, num_ligands, chunk_size):
            if globalFileCount >= cap:
                break
            
            # create the zero-padded subdirectory name
            folderName = str(folderCounter).zfill(len(str(len(proteinLigandPairs))))
            current_save_dir = os.path.join(outputDir, folderName)
            
            if not os.path.exists(current_save_dir):
                os.makedirs(current_save_dir)
            
            subDirKey.append({
                'subdir_code': folderName,
                'uniprot_id': uniprot_id
            })
            
            chunk_slice = group.iloc[i : i+chunk_size]
            is_first_in_chunk = True
            pilotHead = ''
            
            for _, row in chunk_slice.iterrows():
                if globalFileCount >= cap:
                    break
                
                protein_seq = row['Sequence']
                template_path = row['PDB_File_Path']
                compoundId = row['Query ID']
                smiles = row['Query Smiles']
                
                # Build basic Protein dictionary
                protein_entry = {"id": "A", "sequence": protein_seq}
                
                # Handling templates
                has_template = pd.notna(template_path) and os.path.exists(str(template_path))
                if has_template:
                    yaml_template_path = '/project/6002707/Serag/envs/boltz/bioin401/bioin401farm/prod3/templates/' + os.path.basename(template_path)
                    ext = os.path.splitext(template_path)[1].lower()
                    template_key = ext[1:]
                    
                    suffix = "_T_P.yaml" if is_first_in_chunk else "_T.yaml"
                else:
                    suffix = "_P.yaml" if is_first_in_chunk else ".yaml"
                
                fileId = str(globalFileCount).zfill(len(str(len(proteinLigandPairs))))
                filename = f"{fileId}_{uniprot_id}_{compoundId}{suffix}"
                
                if is_first_in_chunk:
                    pilotHead = os.path.splitext(filename)[0]
                
                # MSA LOGIC:
                # If NOT the first file, point to the MSA generated by the Pilot in this same folder
                if not is_first_in_chunk:
                    # Construct absolute path to the expected Pilot MSA on the cluster
                    # We assume the Pilot run output is directed to 'output_pilot'
                    pilot_msa_path = f"/project/6002707/Serag/envs/boltz/bioin401/bioin401farm/results_prod3/0_pilotOutputs/boltz_results_{pilotHead}/msa/{pilotHead}_0.csv"
                    protein_entry["msa"] = pilot_msa_path

                yaml_data = {
                    "sequences": [
                        {"protein": protein_entry},
                        {"ligand": {"id": "B", "smiles": smiles}}
                    ]
                }
                
                if has_template:
                    yaml_data["templates"] = [{template_key: yaml_template_path}]
                
                yaml_data["properties"] = [{"affinity": {"binder": "B"}}]
                
                file_path = os.path.join(current_save_dir, filename)
                with open(file_path, 'w') as f:
                    yaml.dump(yaml_data, f, default_flow_style=False, sort_keys=False)
                
                # After writing the first file, toggle the flag
                is_first_in_chunk = False
                globalFileCount += 1
                
                if globalFileCount % 100 == 0:
                    print(f"Progress: {globalFileCount} files generated.")
            
            folderCounter += 1
            
    key_df = pd.DataFrame(subDirKey)
    key_path = os.path.join(OUTPUT_DIR, 'subdirectory_key.csv')
    key_df.to_csv(key_path, index=False)
    
    print(f"\nSuccess: {globalFileCount} YAMLs written across {folderCounter} folders.")

def main():
    # read processed protein-ligand pairs into a df
    print('Reading data...')
    proteinLigandPairs = pd.read_csv(INPUT_FILEPATH)
    
    print(f'Read {len(proteinLigandPairs)} protein-ligand pairs.')
    
    # generate boltz-ready yaml files using the compiled protein and ligand data
    generateBoltzYamls(proteinLigandPairs, os.path.join(OUTPUT_DIR, 'yamls'), chunk_size=100)

if __name__ == '__main__':
    main()